language: node_js
node_js:
 - 10.15.3

sudo: false

cache:
  directories:
  - node_modules

services:
  - postgresql

before_install:
  - npm install -g npm@latest
  - npm i -g @adonisjs/cli

install: 
  - npm ci

before_script:
  - psql -c 'CREATE DATABASE itinerario;' -U postgres 

script: 
  - adonis migration:run
  - adonis test

provider: heroku
api_key:  
  secure: 8f22d62e-549b-40b0-9120-0a1855a04aaa